In [2]:
import numpy as np
a = np.array([1, 2, 3, 4, 5]) #the np array is going to be of the same type, if one is a string is going to convert
                              #everything inside the array into strings
b = np.array([5, 4, 3, 2, 1])

In [4]:
print a
print b
print np.add(a, b)
print np.subtract(a, b)
print np.dot(a, b)

[1 2 3 4 5]
[5 4 3 2 1]
[6 6 6 6 6]
[-4 -2  0  2  4]
35


In [5]:
c=-a
print np.dot(c,b)

-35
